
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/guoyutong/command-line-tools/sdk/default/openharmony/native/build-tools/cmake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:16 (PROJECT)"
    message: |
      The system is: Darwin - 25.5.0 - arm64
...
